name: Docker Image CI
#触发器设置
on:
  push: # master分支有push时触发此workflow
    branches: [ "master" ]
  pull_request: 
    branches: [ "master" ]

#项目任务，任务之间可以并行调度
jobs:

  build:
    #选择云端运行的环境
    runs-on: ubuntu-latest # job运行的基础环境

    steps: # 一个job由一个或多个step组成
      - name: Build the Docker image
        uses: actions/checkout@v3
        run: sh build.sh
  
  dockerhub:
    #选择云端运行的环境
    runs-on: ubuntu-latest # job运行的基础环境
    
    steps: # 一个job由一个或多个step组成
      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # 三方的action操作， 执行docker login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # 配置dockerhub的认证，在Github项目主页 【Settings】 -> 【Secrets】 添加对应变量
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: haloking/kingbase:v8r3
          
  ghcr:
    #选择云端运行的环境
    runs-on: ubuntu-latest # job运行的基础环境

    steps: # 一个job由一个或多个step组成
      - name: Log in to ghcr Hub
        uses: docker/login-action@v2  # 三方的action操作， 执行docker login
        with:
          username: ${{ github.repository_owner }} 
          password: ${{ secrets.GHCR_USERNAME }}

      - name: Push to ghcr Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: EazonZiu/kingbase:v8r3       
